/*
 * test_docs_example.c - reproduce the worked example of docs/protocol.md S13
 * byte for byte, using the same encoder the firmware uses.
 *
 * ============================ READ THIS ==============================
 * This test compares three independently produced byte streams:
 *   1. what the shared firmware codec + batcher produce from the S13 inputs;
 *   2. a golden vector produced by Node's built-in `chacha20-poly1305`
 *      cipher (the primitive docs/protocol.md S5 names as the server-side
 *      reference) - see the comment above g_expected_datagram;
 *   3. the hex dump inside the BEGIN/END GENERATED EXAMPLE markers of
 *      docs/protocol.md itself, parsed at runtime.
 *
 * (3) is read from disk rather than copied here on purpose: the document is
 * the contract, and copying its bytes into this file would let the two drift
 * silently. The document's dump is machine-generated by the server side
 * (`npm run --workspace @homecsi/protocol print-example`), so if the
 * placeholder is still present - or the markers are missing - the test says
 * so loudly, prints what the firmware produces, and skips that comparison
 * rather than pretending to have verified it.
 *
 * If the document comparison ever FAILS, DO NOT "fix" this test. It means
 * firmware and the contract disagree, which is exactly what this file exists
 * to catch.
 * =====================================================================
 */
#include "harness.h"

#include <ctype.h>

#include "csi_protocol/csi_batcher.h"
#include "csi_protocol/csi_codec.h"
#include "ref_chacha20poly1305.h"

/* --- the S13 inputs, verbatim ---------------------------------------- */

#define EX_NODE_ID 7u
#define EX_BOOT_EPOCH 3u
#define EX_SEQ 42u
#define EX_WALL_CLOCK_US 1700000000000000ull
#define EX_MONO_US 123456789ull

static const uint8_t EX_PSK[HCS_KEY_LEN] = {
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0a,
    0x0b, 0x0c, 0x0d, 0x0e, 0x0f, 0x10, 0x11, 0x12, 0x13, 0x14, 0x15,
    0x16, 0x17, 0x18, 0x19, 0x1a, 0x1b, 0x1c, 0x1d, 0x1e, 0x1f
};

static const uint8_t EX_CSI_DATA[4] = { 0x01, 0x02, 0x03, 0x04 };

/* Golden vector.
 *
 * PROVENANCE: generated by Node 22's `crypto.createCipheriv(
 * 'chacha20-poly1305', ...)` over the plaintext laid out from the S13
 * inputs. Node's cipher is the exact primitive docs/protocol.md S5 names as
 * the server-side reference, so this vector is an independent check of the
 * C encoder + the host reference AEAD, not a self-consistent tautology. */
static const uint8_t g_expected_datagram[101] = {
    0x48, 0x43, 0x53, 0x31, 0x01, 0x01, 0x07, 0x00, 0x03, 0x00, 0x00, 0x00,
    0x2a, 0x00, 0x00, 0x00, 0x07, 0x00, 0x03, 0x00, 0x00, 0x00, 0x2a, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x38, 0xa6, 0x9a, 0xfd, 0xb4, 0xbd, 0x55, 0x3b,
    0x48, 0x03, 0x44, 0x03, 0x22, 0x35, 0x8a, 0xcc, 0x96, 0xd9, 0x5d, 0xb1,
    0xbe, 0xaf, 0x3c, 0x17, 0x55, 0x3b, 0x44, 0x67, 0xcd, 0x72, 0xbe, 0x2e,
    0x5c, 0xd9, 0xfa, 0xe3, 0xd4, 0x3a, 0x01, 0x80, 0x64, 0x96, 0x55, 0xdb,
    0x8d, 0x83, 0xeb, 0x4c, 0x9c, 0xdd, 0x04, 0xcf, 0xc4, 0xe5, 0x8c, 0xed,
    0x10, 0xfd, 0xd6, 0xaa, 0xa6, 0x28, 0xa5, 0x60, 0x1e, 0x5f, 0x50, 0x4f,
    0x85, 0x05, 0x58, 0xfc, 0x49,
};

/* The plaintext, also from Node, checked separately so a failure points at
 * either the layout or the crypto rather than "something is wrong". */
static const uint8_t g_expected_plaintext[57] = {
    0x00, 0x40, 0x1e, 0x18, 0x24, 0x0a, 0x06, 0x00, 0x15, 0xcd, 0x5b, 0x07,
    0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0xaa, 0xbb,
    0xcc, 0xdd, 0xee, 0x01, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff, 0xd6, 0x0b,
    0x01, 0x07, 0x00, 0x06, 0x00, 0xa1, 0xbc, 0xcc, 0x5b, 0x07, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x01, 0x02, 0x03, 0x04,
};

static size_t build_example(uint8_t *out, size_t cap)
{
    hcs_csi_record_t r = {
        .src_mac = { 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0x01 },
        .dst_mac = { 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff },
        .rssi = -42,
        .rate = 11,
        .sig_mode = 1,
        .mcs = 7,
        .bandwidth = 0,
        .channel = 6,
        .secondary_channel = 0,
        .noise_floor = -95,
        .rx_timestamp_us = 123456700ull,
        .csi_format = HCS_CSI_FORMAT_LLTF,
        .csi_len = 4,
        .csi_data = EX_CSI_DATA,
    };

    /* Deliberately goes through the real batcher, not a hand-built buffer, so
     * the example exercises the production path. */
    csi_batcher_t b;
    csi_batcher_init(&b, 16, 200);
    if (csi_batcher_append(&b, &r) != CSI_BATCH_APPENDED) {
        return 0;
    }
    const uint8_t *pt = NULL;
    const size_t pt_len =
        csi_batcher_finalize(&b, EX_WALL_CLOCK_US, EX_MONO_US, true, &pt);

    CHECK_EQ_U64(pt_len, sizeof g_expected_plaintext);
    if (pt_len == sizeof g_expected_plaintext) {
        CHECK_BYTES(pt, g_expected_plaintext, pt_len);
    }

    hcs_header_t hdr = {
        .version = HCS_PROTOCOL_VERSION,
        .msg_type = HCS_MSG_CSI_BATCH,
        .node_id = EX_NODE_ID,
        .boot_epoch = EX_BOOT_EPOCH,
        .seq = EX_SEQ,
    };
    size_t dg_len = 0;
    if (hcs_datagram_seal(out, cap, &dg_len, &hdr, pt, pt_len, EX_PSK,
                          ref_chacha20poly1305_seal, NULL)
        != HCS_OK) {
        return 0;
    }
    return dg_len;
}

static void test_matches_independent_golden_vector(void)
{
    uint8_t dg[HCS_MAX_DATAGRAM_LEN];
    const size_t n = build_example(dg, sizeof dg);
    CHECK_EQ_U64(n, sizeof g_expected_datagram);
    if (n == sizeof g_expected_datagram) {
        CHECK_BYTES(dg, g_expected_datagram, n);
    }
}

/* --- compare against docs/protocol.md, once it has a real dump -------- */

#define GEN_BEGIN "<!-- BEGIN GENERATED EXAMPLE -->"
#define GEN_END "<!-- END GENERATED EXAMPLE -->"
#define PLACEHOLDER "GENERATED_EXAMPLE_PLACEHOLDER"

static char *read_file(const char *path, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        return NULL;
    }
    fseek(f, 0, SEEK_END);
    long sz = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (sz < 0) {
        fclose(f);
        return NULL;
    }
    char *buf = (char *)malloc((size_t)sz + 1);
    if (buf == NULL) {
        fclose(f);
        return NULL;
    }
    size_t got = fread(buf, 1, (size_t)sz, f);
    fclose(f);
    buf[got] = '\0';
    if (out_len) {
        *out_len = got;
    }
    return buf;
}

static int is_hex(char c)
{
    return isxdigit((unsigned char)c) != 0;
}

/* Pull every standalone two-hex-digit token out of `text`. Deliberately
 * liberal: we do not know what annotation format B3's generator will emit,
 * so we look for our byte sequence as a contiguous run inside the tokens. */
static size_t extract_hex_bytes(const char *text, uint8_t *out, size_t cap)
{
    size_t n = 0;
    const char *p = text;
    while (*p != '\0' && n < cap) {
        if (is_hex(p[0]) && is_hex(p[1]) && !is_hex(p[2])
            && (p == text || !is_hex(p[-1]))) {
            char tmp[3] = { p[0], p[1], '\0' };
            out[n++] = (uint8_t)strtoul(tmp, NULL, 16);
            p += 2;
        } else {
            p++;
        }
    }
    return n;
}

static int contains_subsequence(const uint8_t *hay, size_t hay_len,
                                const uint8_t *needle, size_t needle_len)
{
    if (needle_len == 0 || hay_len < needle_len) {
        return 0;
    }
    for (size_t i = 0; i + needle_len <= hay_len; i++) {
        if (memcmp(&hay[i], needle, needle_len) == 0) {
            return 1;
        }
    }
    return 0;
}

static void test_matches_docs_protocol_md(const char *repo_root)
{
    char path[1024];
    snprintf(path, sizeof path, "%s/docs/protocol.md", repo_root);

    size_t len = 0;
    char *doc = read_file(path, &len);
    if (doc == NULL) {
        TEST_NOTICE("could not open %s - skipping the document comparison",
                    path);
        return;
    }

    const char *begin = strstr(doc, GEN_BEGIN);
    const char *end = begin ? strstr(begin, GEN_END) : NULL;
    if (begin == NULL || end == NULL) {
        TEST_NOTICE("docs/protocol.md has no BEGIN/END GENERATED EXAMPLE "
                    "markers - cannot verify S13");
        free(doc);
        return;
    }

    const size_t block_len = (size_t)(end - begin);
    char *block = (char *)malloc(block_len + 1);
    memcpy(block, begin, block_len);
    block[block_len] = '\0';

    if (strstr(block, PLACEHOLDER) != NULL) {
        TEST_NOTICE("docs/protocol.md S13 still contains %s - the normative "
                    "hex dump has NOT been generated, so this test cannot "
                    "check the firmware against the document. The golden "
                    "vector below is what this firmware produces from the "
                    "S13 inputs; have brief B3 generate S13 and confirm it "
                    "matches.",
                    PLACEHOLDER);
        uint8_t dg[HCS_MAX_DATAGRAM_LEN];
        const size_t n = build_example(dg, sizeof dg);
        hcs_test_hexdump("firmware-produced S13 datagram", dg, n);
        free(block);
        free(doc);
        return;
    }

    /* Real dump present: enforce it. */
    static uint8_t tokens[8192];
    const size_t ntokens = extract_hex_bytes(block, tokens, sizeof tokens);

    uint8_t dg[HCS_MAX_DATAGRAM_LEN];
    const size_t n = build_example(dg, sizeof dg);

    const int found = contains_subsequence(tokens, ntokens, dg, n);
    if (!found) {
        TEST_NOTICE("docs/protocol.md S13 hex dump does NOT contain the "
                    "datagram this firmware produces from the S13 inputs. "
                    "This is a contract discrepancy, not a test bug - "
                    "reconcile firmware and document before shipping.");
        hcs_test_hexdump("firmware-produced S13 datagram", dg, n);
    }
    CHECK(found);

    free(block);
    free(doc);
}

int main(int argc, char **argv)
{
    TEST_SUITE("docs/protocol.md S13 example");
    test_matches_independent_golden_vector();
    test_matches_docs_protocol_md((argc > 1) ? argv[1] : "../..");
    return hcs_test_report();
}
